security:
    providers:
        db_provider:
            entity:
                class: Zahar\SportBundle\Entity\User
                property: username

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: sport_calendar_page
            logout: ~

    access_control:
        - { path: ^/(en|ru)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    encoders:
        Zahar\SportBundle\Entity\User: plaintext
